---
- name: Install filebeat via apt
  apt:
    name: filebeat
    state: latest
    update-cache: true
- name: Updating the config file to send logs on kibana (user)
  lineinfile:
    destfile: /etc/filebeat/filebeat.yml
    regexp: '^  #username: "elastic"'
    line: '  username: "elastic"'
- name: Updating the config file to send logs on kibana (password)
  lineinfile:
    destfile: /etc/filebeat/filebeat.yml
    regexp: '^  #password: "changeme"'
    line: '  password: "changeme"'
#- command: filebeat setup; filebeat modules enable nginx

    